import type { SpotCardData } from "@/components/spot-card"

export const MOCK_SPOTS: SpotCardData[] = [
  {
    id: "1",
    name: "Mama Tiffin Centre",
    area: "Koramangala",
    rating: 4.8,
    reviewCount: 124,
    priceRange: "₹",
    tags: ["Home Style", "Tiffin", "Veg"],
    imageUrl: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop",
  },
  {
    id: "2",
    name: "Chai Wala Corner",
    area: "Indiranagar",
    rating: 4.5,
    reviewCount: 89,
    priceRange: "₹",
    tags: ["Snacks", "Budget", "Fast"],
    imageUrl: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400&h=300&fit=crop",
  },
  {
    id: "3",
    name: "Andhra Meals",
    area: "BTM Layout",
    rating: 4.7,
    reviewCount: 203,
    priceRange: "₹₹",
    tags: ["South Indian", "Thali", "Spicy"],
    imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop",
  },
  {
    id: "4",
    name: "Sharma Ji Dhaba",
    area: "HSR Layout",
    rating: 4.6,
    reviewCount: 156,
    priceRange: "₹",
    tags: ["North Indian", "Roti", "Late Night"],
    imageUrl: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop",
  },
  {
    id: "5",
    name: "Quick Bites",
    area: "Marathahalli",
    rating: 4.3,
    reviewCount: 67,
    priceRange: "₹",
    tags: ["Snacks", "Fast Food", "Budget"],
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
  },
  {
    id: "6",
    name: "Udupi Express",
    area: "Whitefield",
    rating: 4.9,
    reviewCount: 312,
    priceRange: "₹₹",
    tags: ["South Indian", "Veg", "Idli"],
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop",
  },
]

export const MOCK_REVIEWS = [
  {
    id: "r1",
    userName: "Priya S.",
    userInitial: "P",
    rating: 5,
    comment: "Absolutely love the thali here. Dal makhani tastes just like home. Must try for students!",
    date: "2 days ago",
    tags: ["Great value", "Tasty food"],
  },
  {
    id: "r2",
    userName: "Arjun K.",
    userInitial: "A",
    rating: 4,
    comment: "Super affordable and filling. Rice is unlimited! Service is fast during lunch rush.",
    date: "1 week ago",
    tags: ["Great value", "Fast service"],
  },
  {
    id: "r3",
    userName: "Meera R.",
    userInitial: "M",
    rating: 5,
    comment: "Hidden gem! Discovered through Spoonful and now it is my go-to. Never thought I'd find something this good near campus.",
    date: "2 weeks ago",
    tags: ["Great value", "Tasty food", "Friendly"],
  },
]
